// pages/index.tsx
import { useThemeContext } from '@/context/ThemeContext';
import { Box, Button } from '@kuma-ui/core';
import { AnimatePresence, motion } from 'framer-motion';
import Head from 'next/head';
import useSWR from 'swr';
import CustomButton from '../components/Button'; // Adjust the import path as necessary

const MotionBox = motion(Box);

export default function Home() {
  const { setIsDark } = useThemeContext();
  const { data, error } = useSWR('/api/sports');

  console.log(data, error);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Box as="main">
        <Box as="h1" color="colors.primary">
          This is your homepage
        </Box>
        <Button onClick={() => setIsDark(v => !v)}>Toggle theme</Button>
        <Box mt={4}>
          <CustomButton variant="filled">Primary</CustomButton>
          <CustomButton variant="stroked">Primary</CustomButton>
          <CustomButton variant="filled" disabled>Primary</CustomButton>
          <CustomButton variant="stroked" disabled>Primary</CustomButton>
          <CustomButton variant="unshielded">Primary</CustomButton>
          <CustomButton variant="unshielded" disabled>Primary</CustomButton>
        </Box>
      </Box>
      <AnimatePresence>
        <MotionBox
          initial={{ opacity: '0', transitionDuration: '0.5s' }}
          animate={{ opacity: '1' }}
        >
          This is animated
        </MotionBox>
      </AnimatePresence>
    </>
  );
}
