// pages/index.tsx
import { useThemeContext } from '@/context/SettingsContext';
import { Box, Text } from '@kuma-ui/core';
import { AnimatePresence, motion } from 'framer-motion';
import Head from 'next/head';
import useSWR from 'swr';
import CustomButton from '@/components/CustomButton'; // Adjust the import path as necessary
import InputSelector from '@/components/InputSelector'; // Adjust the import path as necessary

const MotionBox = motion(Box);

export default function Home() {
  const { setIsDark } = useThemeContext();
  const { data, error } = useSWR('/api/sports');

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Box as="main" className='Tabular' p="16px">
        <Text as="h1" color="colors.primary">
          This is your homepage
        </Text>
        <Box onClick={() => setIsDark(v => !v)}>Toggle theme</Box>
        <Box mt={4}>
          <Text as="h2">Primary - with icon</Text>
          <Box>
            <CustomButton variant="primary" icon>Primary</CustomButton>
            <CustomButton variant="primary" disabled icon>Primary Disabled</CustomButton>
          </Box>
          <Box>
            <CustomButton variant="stroked" icon>Primary</CustomButton>
            <CustomButton variant="stroked" disabled icon>Primary Disabled</CustomButton>
          </Box>
          <Box>
            <CustomButton variant="unshielded">Primary</CustomButton>
            <CustomButton variant="unshielded" disabled>Primary Disabled</CustomButton>
          </Box>
          <Text as="h2">Primary - without icon</Text>
          <Box>
            <CustomButton variant="primary">Primary</CustomButton>
            <CustomButton variant="primary" disabled>Primary Disabled</CustomButton>
          </Box>
          <Box>
            <CustomButton variant="stroked">Primary</CustomButton>
            <CustomButton variant="stroked" disabled>Primary Disabled</CustomButton>
          </Box>
          <Box>
            <CustomButton variant="unshielded">Primary</CustomButton>
            <CustomButton variant="unshielded" disabled>Primary Disabled</CustomButton>
          </Box>
          <Text as="h2">Primary - icon only</Text>
          <Box>
            <CustomButton variant="icon" icon/>
            <CustomButton variant="icon" icon disabled />
          </Box>
        </Box>
        <Box marginBottom="16px">
          <Text as="h2">Grouped selectors</Text>
          <Selector label="Barcelona" withIcon />
          <Selector label="Barcelona" withIcon />
          <Selector label="Barcelona" withIcon />
        </Box>
        <Box marginBottom="16px">
          <Text as="h2">Input Fields / Input Selectors</Text>
          <Box marginBottom="16px">
            <Text as="h3">Empty</Text>
            <InputSelector hintLabel="Hint Label" />
          </Box>
          <Box marginBottom="16px">
            <Text as="h3">Filled</Text>
            <InputSelector hintLabel="Hint Label" itemLabel="Item Label" filled />
          </Box>
          <Box marginBottom="16px">
            <Text as="h3">Empty Disabled</Text>
            <InputSelector hintLabel="Hint Label" disabled />
          </Box>
          <Box marginBottom="16px">
            <Text as="h3">Filled Disabled</Text>
            <InputSelector hintLabel="Hint Label" itemLabel="Item Label" filled disabled />
          </Box>
          <Box marginBottom="16px">
            <Text as="h3">Active</Text>
            <InputSelector hintLabel="Hint Label" itemLabel="Item Label" filled active />
          </Box>
          <Box marginBottom="16px">
            <Text as="h3">Error</Text>
            <InputSelector hintLabel="Hint Label" itemLabel="Item Label" filled error />
          </Box>
        </Box>
      </Box>
      <AnimatePresence>
        <MotionBox
          initial={{ opacity: '0', transitionDuration: '0.5s' }}
          animate={{ opacity: '1' }}
        >
          This is animated
        </MotionBox>
      </AnimatePresence>
    </>
  );
}
